version: "3"
services:

  backend:
    container_name: olengu_backend
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./backend:/backend
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - PORT=80
    networks:
      main:
        ipv4_address: 172.16.42.3

  frontend:
    container_name: olengu_frontend
    build: ./frontend
    restart: on-failure
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      main:
        ipv4_address: 172.16.42.4
  
  gateway:
    container_name: olengu_gateway
    build: ./gateway
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/build:/var/www/html
      - ./gateway/nginx-config:/etc/nginx/sites-enabled/default
    networks:
      main:
        ipv4_address: 172.16.42.2

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      main:
        ipv4_address: 172.16.42.5


networks:
  main:
    driver: bridge
    ipam:
      config:
        -  subnet: 172.16.42.0/28